export const fields = [
  "Finance Manager",
  "Investment Banker",
  "Financial Analyst",
  "Equity Research Analyst",
  "Portfolio Manager",
  "Corporate Treasurer",
  "Risk Manager",
  "Chief Financial Officer (CFO)",
  "Marketing Manager",
  "Brand Manager",
  "Product Manager",
  "Sales Manager",
  "Business Development Manager",
  "Digital Marketing Manager",
  "Market Research Analyst",
  "Operations Manager",
  "Supply Chain Manager",
  "Logistics Manager",
  "Project Manager",
  "Operations Analyst",
  "Consultant (Management)",
  "Strategy Consultant",
  "IT Consultant",
  "Human Resources Manager",
  "Talent Acquisition Manager",
  "HR Business Partner",
  "Learning and Development Manager",
  "Compensation and Benefits Manager",
  "Chief Human Resources Officer (CHRO)",
  "Entrepreneur/Startup Founder",
  "Venture Capitalist",
  "Private Equity Analyst/Manager",
  "Business Analyst",
  "Data Analyst",
  "Chief Executive Officer (CEO)",
  "Chief Operating Officer (COO)",
  "Corporate Strategy Manager",
  "Corporate Development Manager",
  "Healthcare Manager",
  "Pharmaceutical Product Manager",
  "Real Estate Manager",
  "Sustainability Manager",
];
